# ---- Étape 1 : Compilation ----
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . /app
RUN mvn clean package -DskipTests -e

# ---- Étape 2 : Exécution ----
FROM eclipse-temurin:21-jre
WORKDIR /deployments/
COPY --from=build /app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build /app/target/quarkus-app/*.jar /deployments/
COPY --from=build /app/target/quarkus-app/app/ /deployments/app/
COPY --from=build /app/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
CMD ["java", "-jar", "/deployments/quarkus-run.jar"]
