FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# 1. On copie tout ce que Render nous donne
COPY . /app

# 2. On affiche le contenu du dossier /app
RUN echo "=== DEBUT DU CONTENU ===" && ls -la /app && echo "=== FIN DU CONTENU ==="

# 3. On force le plantage pour figer l'écran et lire le résultat du ls
RUN exit 1
